### PR TITLE
Updated SCP 106's AI, Added 173 stingers

### PR DESCRIPTION
**Pull request by VoidImaginedOrder**
Larry can randomly "Emerge" from his pocket dimension. The player has about 7-8 seconds to run from Larry before he can actually perceive them, Added SCP 173 stingers. However these act strangely since 173 can still be seen through walls so you'll hear these when he's across 2 rooms or something. 079 can appear randomly on "BP_Computer" it briefly switches the material to 079's face, than back to the previous material it was.

### CODE REVIEW

**Review by ToyB-Chan — CHANGES_REQUESTED** [review]
- The Behavior Tree is empty. Why have it in the first place?
- What is the point behind the 106WarpPoint class? (Also, it's missing the "BP_" prefix).
- Please refrain from creating events inside collapsed graphs or using collapsed graphs in general. They generally only hide things, which makes the code unintuitive to read.
- Please do not unnecessarily reference blueprint classes inside other blueprint classes. Doing so will only increase the memory footprint and lead to memory management problems sooner rather than later. (For example, you're referencing the BP_PlayerCharacter_PC class for no reason at all).
- I know we currently don't have a way to kill the player, but please just print "kill player" instead of implementing your own way to kill the player. We'll connect it as soon as we implement a common way to kill the player.
- SCP106 is not a patrolling SCP in the original CB game and shouldn't be one in this game either. He is spawned at the player's location after a random amount of time has elapsed, hunts the player for approximately 100 seconds, and then disappears, starting the loop again.
- Please refrain from making any changes to SCP173 as @RadioArtz is currently working on it and will only lead to merge conflicts.
- Please refrain from implementing the jump scare effects inside the AIs. We are currently planning a common solution to handle them.

Because of the issues mentioned above, I will convert this pull request into a draft request for the time being. If you have any questions or need further clarification, please don't hesitate to ask.

**Comment by VoidImaginedOrder** [comment]
106's warp point allows 106 to teleport directly onto it playing his rise animation, it's purely only there to help him warp, while the actor itself is destroyed after about 25 seconds, also the behavior trees are being worked on. And 106 is being revised to be how he Is in CB.

**Comment by VoidImaginedOrder** [comment]
Well when you put it like that, it does sound inefficient, An oversight on my end. I'll take your criticism and apply it to 106 for instance, his patrolling event will be removed and will be replaced with a general recreation in how he acted in CB. As for the get rotation from x vector, that's for 106 to face the player when first warping to them, are you asking for me to utilize another way of achieving this?

**Comment by ToyB-Chan** [comment]
Sounds good. Regarding the rotation, what your current implementation does is it returns the look at rotation to the actors location from (0, 0, 0). If you successfully used it to get the look at rotation between the player and the actor, then that was by pure coincidence. The function you're actually looking for is [FindLookatRotation](https://docs.unrealengine.com/4.27/en-US/BlueprintAPI/Math/Rotator/FindLookatRotation/).

**Comment by RadioArtz** [comment]
Merging this after since all comments by @ToyB-Chan have been adressed!

**Comment by RadioArtz** [comment]
oops, messed up the name but eh whatever

**Pull request merged**
